version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_local_baloncesto
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: baloncesto
    ports:
      - "5432:5432"